name: Test and Build napari-mito-hcs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v2
      with:
        qt: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "napari[all]"
        python -m pip install ".[test]"
    - name: Test with pytest
      run: |
        python -m pytest tests --doctest-modules --junitxml=junit/pytest-results.xml --cov=napari_mito_hcs --cov-report=xml --cov-report=html
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          junit/pytest-results.xml
          htmlcov/
      if: ${{ always() }}
    - name: Build the package
      run: |
        python -m pip install --upgrade pip build setuptools wheel
        python -m build .
    - name: Upload the wheel and sdist
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: |
          dist/napari_mito_hcs-*.whl
          dist/napari_mito_hcs-*.tar.gz
    - name: Build the docs
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[docs]"
        cd docs
        make html
    - name: Upload the HTML
      uses: actions/upload-artifact@v4
      with:
        name: docs-results
        path: |
          docs/_build/html/*
